### ISSUE TITLE
Could we add python3 support?

### ISSUE THREAD

**Issue by yonromai** [tensorflow/metadata#1]
The [tensorflow-metadata pip package](https://pypi.org/project/tensorflow-metadata/) is currently only available for python2 (which means we have to compile the protos manually to enable python3 compatibility). 
Could we fix this?
cc: @ravwojdyla

**Comment by mzinkevi** [comment]
OK, I tried this on ubuntu on my home machine (python 3. and it "worked", installing pip with version 0.6.0. The pip package should be independent of the python2/python3 dependency.

mzinkevi@games:~/working/tf_metadata/python3⟫ python3 -m pip install tensorflow_metadata
Requirement already satisfied: tensorflow_metadata in /usr/local/lib/python3.5/dist-packages (0.6.0)
Requirement already satisfied: googleapis-common-protos in /usr/local/lib/python3.5/dist-packages (from tensorflow_metadata) (1.5.3)
Requirement already satisfied: protobuf<4,>=3.6.0 in /usr/local/lib/python3.5/dist-packages (from tensorflow_metadata) (3.6.0)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from protobuf<4,>=3.6.0->tensorflow_metadata) (20.7.0)
Requirement already satisfied: six>=1.9 in /usr/lib/python3/dist-packages (from protobuf<4,>=3.6.0->tensorflow_metadata) (1.10.0)

mzinkevi@games:~/working/tf_metadata/python3⟫ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorflow_metadata.proto.v0 import schema_pb2
>>> feature = schema_pb2.Feature()
>>> feature.name = "foo"
>>> print(feature)
name: "foo"

>>> 

If you have a process like this, where you tried pip install and it failed, then maybe I can help.

**Comment by yonromai** [comment]
I can't find the box on which the install was failing. 
Since it works on my local machine, I'll close this issue and reopen if the problem shows up again.

Thanks for looking into it @mzinkevi!
